general:
  conf_ver: 1
  debug: true
http_api:
  host: localhost
  port: 8000
input:
  file:
    file_group: "logs/log.txt"
output:
  postgres:
    db: postgresql://postgres:postgres@localhost:5432/warlog
filter:
  postgres_group:
    inputs:
    - file_group
    output: postgres
    pattern: "^(\S+) (\S+) (\S+) \[([\w:/]+\s[+\-]\d{4})\] "(\S+)\s?(\S+)?\s?(\S+)?" (\d{3}|-) (\d+|-)\s?"?([^"]*)"?\s?"?([^"]*)?"?$"  # Apache log regex.
